import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Simple Share",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="md:w-1/2 mx-auto font-mono px-4 md:px-0">
          <nav className=" flex flex-row md:items-center justify-between my-5 md:my-10 border-b border-b-gray-600 pb-3">
            <Link href={"/"} className=" text-4xl font-bold uppercase">
              SimpleShare
            </Link>
            <Link
              href={"/posts/create"}
              className=" text-white bg-black font-medium py-1 px-3 rounded-md w-fit text-2xl"
            >
              +
            </Link>
          </nav>
          <div>{children}</div>
        </section>
      </body>
    </html>
  );
}
