import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Simple Share",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="w-1/2 mx-auto font-mono">
          <nav className=" flex items-center justify-between my-10">
            <Link href={"/"} className=" text-4xl font-bold uppercase">
              SimpleShare
            </Link>
            <Link
              href={"/posts/create"}
              className=" text-white bg-black font-medium p-2 rounded-md"
            >
              Create new post
            </Link>
          </nav>
          <div>{children}</div>
        </section>
      </body>
    </html>
  );
}
